version: '3'
services:
  php:
    container_name: sdi_php
    volumes:
    - ".:/app"
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
    restart: always

  adminer:
    container_name: sdi_adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080

  sdi:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./.docker/sdi:/etc/nginx/conf.d
      - .:/www
    restart: always
    depends_on:
      - php